[package]
name = "rltbl_db_benchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
async-trait = "0.1.89"
clap = "4.6.1"
indexmap = { version = "2.12.0" }
rand = "0.10.1"
rlt = "0.5.0"
# TODO: Get this dependency from crates.io:
rltbl_db = { path = "../rltbl_db" }
serde = "1.0.228"
serde_json = "1.0.150"
slurp = "1.0.1"
tokio = { version = "1.52.3", features = ["full"] }

[[bin]]
name = "rltbl_db_benchmark"
path = "src/main.rs"
