[package]
name = "rltbl_db_benchmarks"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
clap = "4.6.1"
indexmap = { version = "2.12.0" }
rand = "0.9.2"
rlt = "0.5.0"
rltbl_db = { path = ".." }
serde = "1.0.226"
serde_json = "1.0.145"
tokio = { version = "1.52.3", features = ["full"] }
deadpool-postgres = { version = "0.14.1", features = ["rt_tokio_1", "serde"] }
deadpool-sqlite = { version = "0.12.1", features = ["bundled"], }

[[bin]]
name = "rltbl_db_benchmarks"
path = "src/main.rs"
